### PR TITLE
PR #1 Basic Restructure & Authentication handling, Message Formatting…

### PR DESCRIPTION
**Pull request by SN3-K**
This  Pull Request was focused on 4 major areas:

Structure

Authentication Handling*

Message Formatting

Sending

*The main issue I ran into with the authentication handling from the initial concept was the fact that whats app changes the qr code so frequently on slower internet connections it is impossible to render the png fast enough from server to server, instead there will need to be a human element until we find a solution to this problem.

I added a conf.json to allow specific potentially dynamic elements (could change if WA updated their code) , control user (debt collector/admin) settings, as well as a debug flag for kill_on_auth or kill on authentication (don't proceed to send a text)

I have updated the Readme , and added a few other "Support" Files, I will be updating these soon with more information.

### CODE REVIEW

**Comment by SN3-K** [comment]
@bntzio Hey! Any update on this?

**Comment by bntzio** [comment]
Hey @TylerDotPy sorry for the late reply, will check this tomorrow, looks very good, thanks!

**Comment by SN3-K** [comment]
> Hey @TylerDotPy sorry for the late reply, will check this tomorrow, looks very good, thanks!

Awesome glad to hear!

**Review by bntzio — APPROVED** [review]
LG! Thanks @TylerDotPy

**Pull request merged**
